<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>K_OCRIntegrationTests</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Remote.Linq.Newtonsoft.Json" Version="7.3.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\K-OCR\K-OCR.csproj" />
    </ItemGroup>

</Project>
